# Generated by Django 6.0.6 on 2026-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the food item.', max_length=100)),
                ('calories', models.PositiveIntegerField(help_text='Enter the calorie count.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
